package cmd

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// Shell completion is generated by cobra, which already ships a `completion`
// command that PRINTS a script. What it does not do is put that script where
// a shell will read it, which is the step a person actually wants and the
// step they are most likely to get wrong: a completion file in a directory
// the shell never searches is indistinguishable from no completion at all,
// and nothing reports the difference.
//
// So `completion install` writes the file AND says whether the place it
// wrote to is one the shell actually reads. When it is not, it prints the
// exact line to add and where to add it. Claiming to have installed
// something that will never load is precisely the confident lie this project
// refuses elsewhere, and it is cheap to refuse here too.

// completionDirs are the per-shell fallbacks, used when nothing already
// active can be found. Both follow the XDG convention and are owned by the
// user, so installing needs no sudo and cannot collide with a package
// manager's own files.
const (
	zshFallbackDir  = ".local/share/zsh/site-functions"
	bashFallbackDir = ".local/share/bash-completion/completions"
)

// completionTarget is where a script will go and whether the shell will
// actually read it there.
type completionTarget struct {
	dir    string
	file   string
	active bool
	// hint is what the user must do for an inactive directory to start
	// being read. Empty when active.
	hint string
}

func newCompletionInstallCmd(root *cobra.Command) *cobra.Command {
	var shell, dir string
	var dryRun bool

	c := &cobra.Command{
		Use:   "install",
		Short: "Install the completion script where your shell will read it",
		Long: `install writes the completion script into a directory your shell searches,
creating that directory if it does not exist, and overwriting any script this
command wrote before.

It then reports whether the directory is one your shell actually reads. If it
is not, it prints the line to add to your shell's startup file -- a completion
script in an unsearched directory does nothing, and says nothing about it.

Nothing outside the chosen directory is modified: your shell's startup files
are never edited, only quoted.`,
		Args:         cobra.NoArgs,
		SilenceUsage: true,
		RunE: func(c *cobra.Command, _ []string) error {
			return runCompletionInstall(root, shell, dir, dryRun, c.OutOrStdout())
		},
	}
	c.Flags().StringVar(&shell, "shell", "auto",
		`which shell to install for: "zsh", "bash", "all", or "auto" (default: the shell named by $SHELL, falling back to all)`)
	c.Flags().StringVar(&dir, "dir", "",
		"install into this directory instead of the one that would be chosen; implies a single --shell")
	c.Flags().BoolVar(&dryRun, "dry-run", false,
		"report what would be written, and where, without writing it")
	return c
}

func runCompletionInstall(root *cobra.Command, shell, dir string, dryRun bool, out io.Writer) error {
	shells, err := completionShells(shell)
	if err != nil {
		return err
	}
	if dir != "" && len(shells) != 1 {
		return fmt.Errorf("--dir names one directory, so it needs one --shell (got %q, which is %d shells)", shell, len(shells))
	}

	for _, sh := range shells {
		t, err := completionTargetFor(sh, dir, root.Name())
		if err != nil {
			return err
		}
		path := filepath.Join(t.dir, t.file)
		if dryRun {
			fmt.Fprintf(out, "%s: would write %s\n", sh, path)
		} else {
			if err := os.MkdirAll(t.dir, 0o755); err != nil {
				return fmt.Errorf("creating %s: %w", t.dir, err)
			}
			if err := writeCompletion(root, sh, path); err != nil {
				return err
			}
			fmt.Fprintf(out, "%s: wrote %s\n", sh, path)
		}
		if t.active {
			fmt.Fprintf(out, "     active -- open a new shell to pick it up\n")
			if sh == "zsh" {
				// zsh does not rescan fpath on every start; it works from a
				// cached index, and oh-my-zsh only refreshes that once a
				// day. So a correctly installed script can fail to appear
				// for reasons that have nothing to do with the install --
				// which is the one confusing outcome left, and cheap to
				// name. The dump is not deleted here: it is outside the
				// directory this command was asked to write to, and a setup
				// command that removes files elsewhere is a worse bargain
				// than a sentence of explanation.
				fmt.Fprintf(out, "     if it does not appear, zsh has cached its completion index:\n"+
					"       rm -f ~/.zcompdump* && exec zsh\n")
			}
			continue
		}
		fmt.Fprintf(out, "     NOT yet active. %s\n", t.hint)
	}
	return nil
}

// writeCompletion asks cobra for the script. The two shells differ in more
// than a filename: zsh's script must be named _<program> and is autoloaded
// from fpath, while bash's V2 script is sourced by bash-completion under the
// program's plain name.
func writeCompletion(root *cobra.Command, shell, path string) error {
	switch shell {
	case "zsh":
		return root.GenZshCompletionFile(path)
	case "bash":
		return root.GenBashCompletionFileV2(path, true)
	}
	return fmt.Errorf("no completion writer for %q", shell)
}

func completionShells(shell string) ([]string, error) {
	switch shell {
	case "zsh", "bash":
		return []string{shell}, nil
	case "all":
		return []string{"zsh", "bash"}, nil
	case "auto":
		switch filepath.Base(os.Getenv("SHELL")) {
		case "zsh":
			return []string{"zsh"}, nil
		case "bash":
			return []string{"bash"}, nil
		}
		// $SHELL unset or something else entirely: install for both rather
		// than guess. Writing a file the user's shell ignores is harmless;
		// installing for the wrong one and reporting success is not.
		return []string{"zsh", "bash"}, nil
	}
	return nil, fmt.Errorf("unknown shell %q; use zsh, bash, all or auto", shell)
}

func completionTargetFor(shell, dir, program string) (completionTarget, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return completionTarget{}, fmt.Errorf("finding your home directory: %w", err)
	}
	switch shell {
	case "zsh":
		t := completionTarget{file: "_" + program}
		if dir != "" {
			t.dir = dir
			t.active = zshSearches(dir)
		} else if d, ok := writableZshFpathDir(); ok {
			// Already on fpath and writable: completion works with no
			// change to any startup file, which is the outcome worth
			// preferring even though the directory belongs to a package
			// manager rather than to us.
			t.dir, t.active = d, true
		} else {
			t.dir = filepath.Join(home, zshFallbackDir)
			t.active = zshSearches(t.dir)
		}
		if !t.active {
			t.hint = fmt.Sprintf("add this to ~/.zshrc ABOVE the line that runs compinit, then open a new shell:\n       fpath=(%s $fpath)", t.dir)
		}
		return t, nil
	case "bash":
		t := completionTarget{file: program}
		switch {
		case dir != "":
			t.dir = dir
		case os.Getenv("BASH_COMPLETION_USER_DIR") != "":
			t.dir = filepath.Join(os.Getenv("BASH_COMPLETION_USER_DIR"), "completions")
		default:
			t.dir = filepath.Join(home, bashFallbackDir)
		}
		// bash-completion 2.x reads the user directory on its own, so the
		// only question is whether bash-completion is installed at all --
		// without it, nothing loads the file however it is named.
		t.active = bashCompletionInstalled()
		if !t.active {
			t.hint = "bash-completion does not appear to be installed, and bash loads these files through it.\n       On macOS: brew install bash-completion@2, then follow the caveats it prints."
		}
		return t, nil
	}
	return completionTarget{}, fmt.Errorf("unknown shell %q", shell)
}

// writableZshFpathDir returns the first directory on the user's real fpath
// that we could write to, preferring the conventional completion directories.
//
// It asks zsh itself, interactively, because fpath is assembled by the user's
// own startup files -- a framework such as oh-my-zsh adds several -- and
// there is no way to know it from the outside. A guess here would be the
// whole failure this command exists to avoid: it is exactly the difference
// between a file that completes and a file that sits there.
func writableZshFpathDir() (string, bool) {
	dirs, ok := zshFpath()
	if !ok {
		return "", false
	}
	home, _ := os.UserHomeDir()
	best, bestScore := "", 0
	for _, d := range dirs {
		score := scoreZshCompletionDir(d, home)
		if score > bestScore && dirIsWritable(d) {
			best, bestScore = d, score
		}
	}
	return best, best != ""
}

// scoreZshCompletionDir ranks a directory on fpath as a place to install a
// completion script. 0 means "do not use".
//
// Two rules earned their place by getting this wrong. A directory with
// "cache" in its path is refused outright: oh-my-zsh keeps one on fpath and
// empties it, so a script installed there works until it silently does not,
// which is the worst of the available failures. And a directory under the
// user's home wins over a system one even when the system one is more
// conventionally named, because it needs no privileges, survives a package
// manager upgrading the shell out from under it, and belongs to the person
// who ran the install.
func scoreZshCompletionDir(dir, home string) int {
	if strings.Contains(dir, "/cache/") || strings.HasSuffix(dir, "/cache") {
		return 0
	}
	base := 0
	switch {
	case strings.HasSuffix(dir, "site-functions"):
		base = 2
	case strings.HasSuffix(dir, "completions"):
		base = 1
	default:
		// Some other fpath entry -- a framework's function library, say.
		// Completion scripts do not belong there.
		return 0
	}
	if home != "" && strings.HasPrefix(dir, home+string(os.PathSeparator)) {
		base += 10
	}
	return base
}

// zshFpath asks zsh itself, interactively, what its fpath is.
//
// It has to be asked rather than guessed: fpath is assembled by the user's
// own startup files, and a framework such as oh-my-zsh adds several entries
// that no amount of convention would predict. Guessing here would produce
// exactly the failure this command exists to prevent -- a file written to a
// directory nothing reads, reported as a success.
func zshFpath() ([]string, bool) {
	zsh, err := exec.LookPath("zsh")
	if err != nil {
		return nil, false
	}
	outBytes, err := exec.Command(zsh, "-i", "-c", "print -l $fpath").Output()
	if err != nil {
		return nil, false
	}
	var dirs []string
	for _, line := range strings.Split(string(outBytes), "\n") {
		if d := strings.TrimSpace(line); d != "" {
			dirs = append(dirs, d)
		}
	}
	return dirs, len(dirs) > 0
}

// zshSearches reports whether dir is on the fpath zsh would actually use.
func zshSearches(dir string) bool {
	dirs, ok := zshFpath()
	if !ok {
		return false
	}
	want := filepath.Clean(dir)
	for _, d := range dirs {
		if filepath.Clean(d) == want {
			return true
		}
	}
	return false
}

func dirIsWritable(dir string) bool {
	info, err := os.Stat(dir)
	if err != nil || !info.IsDir() {
		return false
	}
	f, err := os.CreateTemp(dir, ".writetest")
	if err != nil {
		return false
	}
	name := f.Name()
	f.Close()
	os.Remove(name)
	return true
}

// bashCompletionInstalled reports whether the bash-completion package is
// present. bash does not read a completions directory by itself; that
// machinery is bash-completion's, and without it the file we write is inert.
func bashCompletionInstalled() bool {
	for _, p := range []string{
		"/opt/homebrew/etc/profile.d/bash_completion.sh",
		"/usr/local/etc/profile.d/bash_completion.sh",
		"/usr/share/bash-completion/bash_completion",
		"/etc/bash_completion",
	} {
		if _, err := os.Stat(p); err == nil {
			return true
		}
	}
	return false
}
